Repository Ensembl/ensj-healthcheck, pull requests merged in 2019-06, with the labels that each got.

#187 New compara HC to check that alignments are complete
  src/org/ensembl/healthcheck/testcase/compara/CheckGenomicAlignCoverage.java
  src/org/ensembl/healthcheck/testgroup/ComparaGenomicOnly.java
Labels: enhancement

#186 Improved performance by additional flag and merged queries
  src/org/ensembl/healthcheck/testcase/compara/CheckConservationScorePerBlock.java
Labels: enhancement

#191 We decided to remove the AssemblyExceptionTableSeqMapping hc from the…
  src/org/ensembl/healthcheck/testgroup/GenebuildPostHandoverService.java
Labels: bau

#190 Search for the compara master database with wildcards too
  src/org/ensembl/healthcheck/testcase/AbstractControlledTable.java
  src/org/ensembl/healthcheck/testcase/EnsTestCase.java
  src/org/ensembl/healthcheck/testcase/eg_compara/AbstractControlledRows.java
  src/org/ensembl/healthcheck/testcase/eg_compara/ControlledTableDnafrag.java
  src/org/ensembl/healthcheck/testcase/eg_core/SeqRegionAttribForPolyploidGenome.java
  src/org/ensembl/healthcheck/testcase/eg_core/SeqRegionAttribForPolyploidGenomeToplevelOnly.java
  src/org/ensembl/healthcheck/testcase/eg_core/SeqRegionsConsistentWithComparaMaster.java
Labels: enhancement

#189 Make ensj-healthcheck compatible with OpenJDK v9+
  src/org/ensembl/healthcheck/Debug.java
Labels: bug
